env:
  global:
    - TRAVIS_BRANCH: "stable/1.3.5" # fake this so get_ci_vars() does not error out
    - CONAN_USERNAME: "conan"
    - CONAN_UPLOAD: "https://api.bintray.com/conan/ecashptyltd/public-conan"

linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7 CONAN_ARCHS=armv7hf

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
